### ISSUE TITLE
docker 打包出现问题

### ISSUE THREAD

**Issue by GLWJP** [TencentCloud/cls-console-sdk#1]
75.75  ENOENT  ENOENT: no such file or directory, open '/root/.local/share/pnpm/store/v3/files/a7/d0558bd89c42f795dd42328f740831ca53bc25-index.json'
75.75 
75.75 
75.75 
------
Dockerfile:10
--------------------
   8 |     
   9 |     RUN npm i -g pnpm pm2
  10 | >>> RUN pnpm recursive install
  11 |     RUN pnpm run build
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm recursive install" did not complete successfully: exit code: 1

**Comment by ianhu92** [comment]
已修改dockerfile，请pull后重试。
